version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: camunda_spring_postgres
    restart: always
    environment:
      POSTGRES_DB: camunda
      POSTGRES_USER: camunda
      POSTGRES_PASSWORD: camunda_password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U camunda"]
      interval: 10s
      retries: 5

  camunda:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: camunda_springboot
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/camunda
      SPRING_DATASOURCE_USERNAME: camunda
      SPRING_DATASOURCE_PASSWORD: camunda_password
    ports:
      - "8080:8080"

volumes:
  pg_data: