version: "3.8"

services:
  cib7-platform:
    build: .
    container_name: cib7-platform
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod  # Change to 'dev' for development mode, or 'prod' for production mode
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_URL: jdbc:postgresql://cib7-db:5432/camunda
      # DB_HOST: camunda-db
      # DB_PORT: 5432
    depends_on:
      cib7-db:
        condition: service_healthy
    networks:
      - camunda-network

  cib7-db:
    image: postgres:16
    container_name: cib7-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: camunda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - camunda-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d camunda"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - camunda-network

  cib7-adminer:
    image: adminer
    container_name: cib7-adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      cib7-db:
        condition: service_healthy
    networks:
      - camunda-network

networks:
  camunda-network:
    driver: bridge

volumes:
  camunda-db-data: